### ISSUE TITLE
ShiroProperties 没有注入成功

### ISSUE THREAD

**Issue by johntostring** [boyazuo/shiro-spring-boot#1]
按照你的代码我自己写了一遍，但我只是把`ShiroManager`省去了，都写到`ShiroAutoConfiguration`里了。
然而启动项目，报`java.lang.NullPointerException`，发生在`ShiroAutoConfiguration.realm()`

```
Class<?> realmClass = properties.getRealm();
```

加入断点后，发现`ShiroProperties` 是 `null`，对Spring boot不了解，求指教，谢谢！

**Comment by boyazuo** [comment]
Shiro的这些bean存在依赖关系，把bean全都写到ShiroAutoConfiguration里的话，LifecycleBeanPostProcessor首先会被创建放入ctx中，在同一个类里的其他bean也会紧接着被创建，这样这些方法都会在Autowired之前被调用，最后才会实例化并注入properties对象。所以，方法中取properties会是null。
也是因为这个原因，我把那几个bean单独放到了ShiroManager中。

**Comment by johntostring** [comment]
多谢！:smile:
